### ISSUE TITLE
Link.equals throws NPE on null object

### ISSUE THREAD

**Issue by darkehis** [jbotsim/JBotSim#65] opened 2019-07-10 08:55 UTC
The following code throws a `NullPointerException`:
```
Link link = new Link(New Node(), new Node());
link.equals(null);
```
Is that normal ?

**Comment by remikey** [comment] 2019-07-10 12:21
No, it is not. Thank you for the report! :-)

Merged into `develop`:
* `Link.equals(null)` returns false instead of throwing NPE;
* Related UT added in order to check that the issue is not present on main objects (`Node`, `Link`, `Color`).

**Closed** 2019-09-10 13:47 UTC
Labels: bug, ready
