### ISSUE TITLE
onPreStart() needed

### ISSUE THREAD

**Issue by jschoete** [jbotsim/JBotSim#82] opened 2019-11-07 10:36 UTC
In the same idea of onPreClock(), onPreStart() can be useful.

**Comment by remikey** [comment] 2019-11-07 15:07
I am currently investigating on #56 . I think it is the same feature as what you are asking for, isn't it?

**Comment by jschoete** [comment] 2019-11-07 15:19
It seems similar yes. 
To be precise : nodes seem to have an order in which they execute onStart() (the order of their ID's ?), which resulted in my program needing to create nodes in some specific order, or it wouldn't work (or I had to use some other roundabout solution). An onPreStart() might be more intuitive (especially since there's an onPreClock() already).

**Comment by remikey** [comment] 2019-11-07 15:36
Although we do not have a specification on this, the `onStart()` methods are actually called with respect to the order in which the nodes have been added. Yet, the implemented algorithms should not count on this. 
In some cases, we indeed need to use some tricky workarounds. 
For such reason, there should soon be a `onInit()` which will be called _once_, when the `Topology` has been initialized (_i.e._ all nodes are added to the `Topology` and are "ready to work").

Please note that, the `onStart()` method will continue to be called after any  use of the `pause()`/`resume()` pair.

Let me know if that's enough for you. I will mark this issue as a duplicate, and close it.
Also, feel free to come and discuss this issue with me.

**Comment by jschoete** [comment] 2019-11-08 08:50
That's enough for me.

**Comment by remikey** [comment] 2019-11-08 08:53
Closing issue as it is a duplicate of #56 .

**Closed by remikey** 2019-11-08 08:53 UTC
Labels: duplicate
